#include "ClassCommandManager.hpp"

#define ORIENT_ANGLE_ACT1 90.0f
#define INIT_ANGLE_ACT1   0.0f
#define RESET_ANGLE_ACT1  180.0f

#define ORIENT_ANGLE_ACT2 90.0f
#define INIT_ANGLE_ACT2   0.0f
#define RESET_ANGLE_ACT2  180.0f

#define ORIENT_ANGLE_ACT3 90.0f
#define INIT_ANGLE_ACT3   0.0f
#define RESET_ANGLE_ACT3  180.0f

#define ORIENT_ANGLE_ACT4 90.0f
#define INIT_ANGLE_ACT4   0.0f
#define RESET_ANGLE_ACT4  180.0f


Actionneur ACT1(
    UNIT_PWM_1, SIGNAL_PWM_1, TIMER_PWM_1, OPR_PWM_1,
    PIN_PW_1_ACT1,
    UNIT_PWM_2, SIGNAL_PWM_2, TIMER_PWM_2, OPR_PWM_2,
    PIN_PW_2_ACT1,
    PIN_VERIN_1_ACT1, PIN_VERIN_2_ACT1, PIN_VERIN_3_PWM_ACT1,
    ORIENT_ANGLE_ACT1, INIT_ANGLE_ACT1, RESET_ANGLE_ACT1,
    "ACT1"
);
Actionneur ACT2(
    UNIT_PWM_3, SIGNAL_PWM_3, TIMER_PWM_3, OPR_PWM_3,
    PIN_PW_1_ACT2,
    UNIT_PWM_4, SIGNAL_PWM_4, TIMER_PWM_4, OPR_PWM_4,
    PIN_PW_2_ACT2,
    PIN_VERIN_1_ACT2, PIN_VERIN_2_ACT2, PIN_VERIN_3_PWM_ACT2,
    ORIENT_ANGLE_ACT2, INIT_ANGLE_ACT2, RESET_ANGLE_ACT2,
    "ACT2"
);
Actionneur ACT3(
    UNIT_PWM_5, SIGNAL_PWM_5, TIMER_PWM_5, OPR_PWM_5,
    PIN_PW_1_ACT3,
    UNIT_PWM_6, SIGNAL_PWM_6, TIMER_PWM_6, OPR_PWM_6,
    PIN_PW_2_ACT3,
    PIN_VERIN_1_ACT3, PIN_VERIN_2_ACT3, PIN_VERIN_3_PWM_ACT3,
    ORIENT_ANGLE_ACT3, INIT_ANGLE_ACT3, RESET_ANGLE_ACT3,
    "ACT3"
);
Actionneur ACT4(
    UNIT_PWM_7, SIGNAL_PWM_7, TIMER_PWM_7, OPR_PWM_7,
    PIN_PW_1_ACT4,
    UNIT_PWM_8, SIGNAL_PWM_8, TIMER_PWM_8, OPR_PWM_8,
    PIN_PW_2_ACT4,
    PIN_VERIN_1_ACT4, PIN_VERIN_2_ACT4, PIN_VERIN_3_PWM_ACT4,
    ORIENT_ANGLE_ACT4, INIT_ANGLE_ACT4, RESET_ANGLE_ACT4,
    "ACT4"
);

ClassCommandManager CommandManager;

void setup(){
    Serial.begin(115200);
    Serial1.begin(115200);
    ACT1.init(3,4096, 1);
    ACT2.init(3,4096, 1);
    ACT3.init(3,4096, 1);
    ACT4.init(3,4096, 1);
    CommandManager.StartCommandTask();
}