#include "ClassCommandManager.hpp"

ClassCommandManager CommandManager;

Actionneur ACT1(
    PIN_ASC_SNS_1,
    UNIT_PWM_1, SIGNAL_PWM_1, TIMER_PWM_1, OPR_PWM_1,
    PIN_PW_1_ACT1,
    UNIT_PWM_2, SIGNAL_PWM_2, TIMER_PWM_2, OPR_PWM_2,
    PIN_PW_2_ACT1,
    PIN_VERIN_1_ACT1, PIN_VERIN_2_ACT1, PIN_VERIN_3_PWM_ACT1,
    PIN_ASC_STP_ACT1, PIN_ASC_DIR_ACT1, "asc1", true
);
Actionneur ACT2(
    PIN_ASC_SNS_2,
    UNIT_PWM_3, SIGNAL_PWM_3, TIMER_PWM_3, OPR_PWM_3,
    PIN_PW_1_ACT2,
    UNIT_PWM_4, SIGNAL_PWM_4, TIMER_PWM_4, OPR_PWM_4,
    PIN_PW_2_ACT2,
    PIN_VERIN_1_ACT2, PIN_VERIN_2_ACT2, PIN_VERIN_3_PWM_ACT2,
    PIN_ASC_STP_ACT2, PIN_ASC_DIR_ACT2, "asc2", true
);
Actionneur ACT3(
    PIN_ASC_SNS_3,
    UNIT_PWM_5, SIGNAL_PWM_5, TIMER_PWM_5, OPR_PWM_5,
    PIN_PW_1_ACT3,
    UNIT_PWM_6, SIGNAL_PWM_6, TIMER_PWM_6, OPR_PWM_6,
    PIN_PW_2_ACT3,
    PIN_VERIN_1_ACT3, PIN_VERIN_2_ACT3, PIN_VERIN_3_PWM_ACT3,
    PIN_ASC_STP_ACT3, PIN_ASC_DIR_ACT3, "asc3", true
);
Actionneur ACT4(
    PIN_ASC_SNS_4,
    UNIT_PWM_7, SIGNAL_PWM_7, TIMER_PWM_7, OPR_PWM_7,
    PIN_PW_1_ACT4,
    UNIT_PWM_8, SIGNAL_PWM_8, TIMER_PWM_8, OPR_PWM_8,
    PIN_PW_2_ACT4,
    PIN_VERIN_1_ACT4, PIN_VERIN_2_ACT4, PIN_VERIN_3_PWM_ACT4,
    PIN_ASC_STP_ACT4, PIN_ASC_DIR_ACT4, "asc4", true
);

void setup(){
    ACT1.init(3,4096, 1);
    ACT2.init(3,4096, 1);
    ACT3.init(3,4096, 1);
    ACT4.init(3,4096, 1);
    CommandManager.StartCommandTask();
}